module.exports = (app, container) => {
  const { verifyToken } = container.resolve('middleware')
  app.use(verifyToken)
  require('./feedApi')(app, container)
  require('./commentApi')(app, container)
  require('./reactionApi')(app, container)
  require('./uploadApi')(app, container)
  require('./userApi')(app, container)
  require('./groupApi')(app, container)
  require('./userGroupApi')(app, container)
  require('./modApi')(app, container)
  require('./notificationApi')(app, container)
  require('./friendApi')(app, container)
  require('./fcmtokenApi')(app, container)
  require('./chatApi')(app, container)
}
