const { initDI } = require('./di')
const { name } = require('../package.json')
const config = require('./config')
const logger = require('./logger')
const middleware = require('./middleware')
const server = require('./server')
const controller = require('./controller')
const redisHelper = require('./redisHelper')
const helper = require('./helper')
const handleCache = require('./handleCache')
const updateCache = require('./updateCache')
const repo = require('./repo')
const { start } = require('./cache')
const EventEmitter = require('events').EventEmitter
const mediator = new EventEmitter()
logger.d(`${name} Service`)
mediator.once('di.ready', async container => {
  console.log('di.ready, starting connect db ', config.dbSettings)
  container.registerValue('config', config)
  container.registerValue('logger', logger)
  container.registerValue('mediator', mediator)
  const cache = await start(container)
  logger.d('redis.ready, starting server')
  container.registerValue('redis', cache)
  container.registerValue('redisHelper', redisHelper(container))
  container.registerValue('helper', helper(container))
  container.registerValue('handleCache', handleCache(container))
  const repository = repo.connect(container)
  container.registerValue('repo', repository)
  container.registerValue('controller', controller(container))
  container.registerValue('middleware', middleware(container))
  server.start(container).then(app => {
    logger.d('Server started at port ', app.address().port)
    updateCache(container)
  })
})
initDI(mediator)
